// Sample winner data - UPDATE WITH ACTUAL WINNER INFORMATION
// These are placeholder names and details for the winner photos

export const sampleWinners = [
  {
    id: '1',
    name: 'Michael R.',
    oxfordHouse: 'Austin House',
    monthAwarded: 'January',
    year: 2024,
    photoUrl: '/winners/IMG_0813.JPG',
    story: 'Celebrating 30 days of sobriety and new beginnings',
  },
  {
    id: '2',
    name: 'Sarah T.',
    oxfordHouse: 'Cedar Park House',
    monthAwarded: 'February',
    year: 2024,
    photoUrl: '/winners/IMG_0814.JPG',
    story: 'Building a foundation for lasting recovery',
  },
  {
    id: '3',
    name: 'David L.',
    oxfordHouse: 'Round Rock House',
    monthAwarded: 'March',
    year: 2024,
    photoUrl: '/winners/IMG_0815.JPG',
    story: 'Finding hope and community in recovery',
  },
  {
    id: '4',
    name: 'Jennifer M.',
    oxfordHouse: 'Georgetown House',
    monthAwarded: 'April',
    year: 2024,
    photoUrl: '/winners/IMG_0816.JPG',
    story: 'Committed to change and personal growth',
  },
  {
    id: '5',
    name: 'Robert K.',
    oxfordHouse: 'Pflugerville House',
    monthAwarded: 'May',
    year: 2024,
    photoUrl: '/winners/IMG_0817.JPG',
    story: 'Embracing recovery one day at a time',
  },
  {
    id: '6',
    name: 'Amanda P.',
    oxfordHouse: 'Manor House',
    monthAwarded: 'June',
    year: 2024,
    photoUrl: '/winners/IMG_0818.JPG',
    story: 'Grateful for this new chapter',
  },
  {
    id: '7',
    name: 'Christopher W.',
    oxfordHouse: 'Lakeway House',
    monthAwarded: 'July',
    year: 2024,
    photoUrl: '/winners/IMG_0819.JPG',
    story: 'Building a life worth living',
  },
  {
    id: '8',
    name: 'Lisa H.',
    oxfordHouse: 'Austin House',
    monthAwarded: 'August',
    year: 2024,
    photoUrl: '/winners/IMG_0820.JPG',
    story: 'Finding strength in community',
  },
  {
    id: '9',
    name: 'James D.',
    oxfordHouse: 'Cedar Park House',
    monthAwarded: 'September',
    year: 2024,
    photoUrl: '/winners/IMG_0821.JPG',
    story: 'Proud of my progress',
  },
  {
    id: '10',
    name: 'Michelle S.',
    oxfordHouse: 'Round Rock House',
    monthAwarded: 'October',
    year: 2024,
    photoUrl: '/winners/IMG_0822.JPG',
    story: 'Every day is a new beginning',
  },
  {
    id: '11',
    name: 'Daniel B.',
    oxfordHouse: 'Georgetown House',
    monthAwarded: 'November',
    year: 2024,
    photoUrl: '/winners/IMG_0823.JPG',
    story: 'Grateful for this opportunity',
  },
  {
    id: '12',
    name: 'Patricia G.',
    oxfordHouse: 'Pflugerville House',
    monthAwarded: 'December',
    year: 2024,
    photoUrl: '/winners/IMG_0824.JPG',
    story: 'Ending the year with hope',
  },
  {
    id: '13',
    name: 'Kevin F.',
    oxfordHouse: 'Manor House',
    monthAwarded: 'January',
    year: 2025,
    photoUrl: '/winners/IMG_0825.JPG',
    story: 'Starting the new year strong',
  },
  {
    id: '14',
    name: 'Rachel N.',
    oxfordHouse: 'Lakeway House',
    monthAwarded: 'February',
    year: 2025,
    photoUrl: '/winners/IMG_0826.JPG',
    story: 'Committed to my recovery journey',
  },
  {
    id: '15',
    name: 'Brandon C.',
    oxfordHouse: 'Austin House',
    monthAwarded: 'March',
    year: 2025,
    photoUrl: '/winners/IMG_0827.JPG',
    story: 'Building a brighter future',
  },
  {
    id: '16',
    name: 'Nicole V.',
    oxfordHouse: 'Cedar Park House',
    monthAwarded: 'April',
    year: 2025,
    photoUrl: '/winners/IMG_0828.JPG',
    story: 'Grateful for support',
  },
  {
    id: '17',
    name: 'Anthony R.',
    oxfordHouse: 'Round Rock House',
    monthAwarded: 'May',
    year: 2025,
    photoUrl: '/winners/IMG_0829.JPG',
    story: 'Living in recovery',
  },
  {
    id: '18',
    name: 'Stephanie L.',
    oxfordHouse: 'Georgetown House',
    monthAwarded: 'June',
    year: 2025,
    photoUrl: '/winners/IMG_0830.JPG',
    story: 'Finding my path forward',
  },
  {
    id: '19',
    name: 'Marcus J.',
    oxfordHouse: 'Pflugerville House',
    monthAwarded: 'July',
    year: 2025,
    photoUrl: '/winners/IMG_0832.JPG',
    story: 'Celebrating progress',
  },
  {
    id: '20',
    name: 'Ashley K.',
    oxfordHouse: 'Manor House',
    monthAwarded: 'August',
    year: 2025,
    photoUrl: '/winners/IMG_0833.JPG',
    story: 'Thankful for this blessing',
  },
  {
    id: '21',
    name: 'Tyler M.',
    oxfordHouse: 'Lakeway House',
    monthAwarded: 'September',
    year: 2025,
    photoUrl: '/winners/IMG_0834.JPG',
    story: 'Building confidence daily',
  },
]
